In [ ]:
!pip install requests beautifulsoup4 pandas lxml -q

In [ ]:
import requests
from bs4 import BeautifulSoup

url = "https://ar.wikipedia.org/wiki/كأس_العالم_2026"
headers = {"User-Agent": "Mozilla/5.0 (educational scraping)"}

response = requests.get(url, headers=headers)
response.raise_for_status()
soup = BeautifulSoup(response.text, "lxml")
print(response.status_code, len(response.text))

200 2553879

In [ ]:
import pandas as pd

tables = pd.read_html(response.text)  # بترجع ليستة بكل الجداول في الصفحة
print(f"عدد الجداول: {len(tables)}")

for i, t in enumerate(tables):
    print(i, t.columns.tolist()[:5], t.shape)

/tmp/ipykernel_9055/2932412099.py:3: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(response.text)  # بترجع ليستة بكل الجداول في الصفحة

عدد الجداول: 135
0 ['FIFA World Cup 26 (بالإنجليزية) Copa Mundial de la FIFA 2026 (بالإسبانية) Coupe du Monde FIFA 2026 (بالفرنسية)', 'FIFA World Cup 26 (بالإنجليزية) Copa Mundial de la FIFA 2026 (بالإسبانية) Coupe du Monde FIFA 2026 (بالفرنسية).1'] (21, 2)
1 [0] (9, 1)
2 ['المرحلة', 'الدور/الجولة', 'التاريخ'] (9, 3)
3 ['الجولة', 'المواجهات', 'المجموعات', 'التاريخ'] (17, 4)
4 ['مسموح لهم للتصويت', 'ممنوع من التصويت'] (4, 2)
5 [('العرض', 'العرض'), ('الأصوات', 'الجولة 1'), ('الأصوات', 'Unnamed: 2_level_1')] (6, 3)
6 ['المدينة', 'الملعب', 'عدد المباريات', 'الطاقة الاستيعابية', 'صورة'] (16, 5)
7 [0, 1, 2] (1, 3)
8 ['الوعاء 1', 'الوعاء 2', 'الوعاء 3', 'الوعاء 4'] (1, 4)
9 [0] (1, 1)
10 ['م', 'الفريقعنت', 'لعب', 'ف', 'ت'] (4, 11)
11 ['المكسيك', '2–0', 'جنوب إفريقيا'] (1, 3)
12 ['كوريا الجنوبية', '2–1', 'التشيك'] (1, 3)
13 ['التشيك', '1–1', 'جنوب إفريقيا'] (1, 3)
14 ['المكسيك', '1–0', 'كوريا الجنوبية'] (1, 3)
15 ['التشيك', '0–3', 'المكسيك'] (1, 3)
16 ['جنوب إفريقيا', '1–0', 'كوريا الجنوبية'] (1, 3)
17 ['م', 'الفريقعنت', 'لعب', 'ف', 'ت'] (4, 11)
18 ['كندا', '1–1', 'البوسنة والهرسك'] (1, 3)
19 ['قطر', '1–1', 'سويسرا'] (1, 3)
20 ['سويسرا', '4–1', 'البوسنة والهرسك'] (1, 3)
21 ['كندا', '6–0', 'قطر'] (1, 3)
22 ['سويسرا', '2–1', 'كندا'] (1, 3)
23 ['البوسنة والهرسك', '3–1', 'قطر'] (1, 3)
24 ['م', 'الفريقعنت', 'لعب', 'ف', 'ت'] (4, 11)
25 ['البرازيل', '1–1', 'المغرب'] (1, 3)
26 ['هايتي', '0–1', 'إسكتلندا'] (1, 3)
27 ['إسكتلندا', '0–1', 'المغرب'] (1, 3)
28 ['البرازيل', '3–0', 'هايتي'] (1, 3)
29 ['إسكتلندا', '0–3', 'البرازيل'] (1, 3)
30 ['المغرب', '4–2', 'هايتي'] (1, 3)
31 ['م', 'الفريقعنت', 'لعب', 'ف', 'ت'] (4, 11)
32 ['الولايات المتحدة', '4–1', 'باراغواي'] (1, 3)
33 ['أستراليا', '2–0', 'تركيا'] (1, 3)
34 ['الولايات المتحدة', '2–0', 'أستراليا'] (1, 3)
35 ['تركيا', '0–1', 'باراغواي'] (1, 3)
36 ['تركيا', '3–2', 'الولايات المتحدة'] (1, 3)
37 ['باراغواي', '0–0', 'أستراليا'] (1, 3)
38 ['م', 'الفريقعنت', 'لعب', 'ف', 'ت'] (4, 11)
39 ['ألمانيا', '7–1', 'كوراساو'] (1, 3)
40 ['ساحل العاج', '1–0', 'الإكوادور'] (1, 3)
41 ['ألمانيا', '2–1', 'ساحل العاج'] (1, 3)
42 ['الإكوادور', '0–0', 'كوراساو'] (1, 3)
43 ['كوراساو', '0–2', 'ساحل العاج'] (1, 3)
44 ['الإكوادور', '2–1', 'ألمانيا'] (1, 3)
45 ['م', 'الفريقعنت', 'لعب', 'ف', 'ت'] (4, 11)
46 ['هولندا', '2–2', 'اليابان'] (1, 3)
47 ['السويد', '5–1', 'تونس'] (1, 3)
48 ['هولندا', '5–1', 'السويد'] (1, 3)
49 ['تونس', '0–4', 'اليابان'] (1, 3)
50 ['اليابان', '1–1', 'السويد'] (1, 3)
51 ['تونس', '1–3', 'هولندا'] (1, 3)
52 ['م', 'الفريقعنت', 'لعب', 'ف', 'ت'] (4, 11)
53 ['بلجيكا', '1–1', 'مصر'] (1, 3)
54 ['إيران', '2–2', 'نيوزيلندا'] (1, 3)
55 ['بلجيكا', '0–0', 'إيران'] (1, 3)
56 ['نيوزيلندا', '1–3', 'مصر'] (1, 3)
57 ['مصر', '1–1', 'إيران'] (1, 3)
58 ['نيوزيلندا', '1–5', 'بلجيكا'] (1, 3)
59 ['م', 'الفريقعنت', 'لعب', 'ف', 'ت'] (4, 11)
60 ['إسبانيا', '0–0', 'الرأس الأخضر'] (1, 3)
61 ['السعودية', '1–1', 'أوروغواي'] (1, 3)
62 ['إسبانيا', '0−4', 'السعودية'] (1, 3)
63 ['أوروغواي', '2–2', 'الرأس الأخضر'] (1, 3)
64 ['الرأس الأخضر', '0–0', 'السعودية'] (1, 3)
65 ['أوروغواي', '0–1', 'إسبانيا'] (1, 3)
66 ['م', 'الفريقعنت', 'لعب', 'ف', 'ت'] (4, 11)
67 ['فرنسا', '3–1', 'السنغال'] (1, 3)
68 ['العراق', '1–4', 'النرويج'] (1, 3)
69 ['فرنسا', '3–0', 'العراق'] (1, 3)
70 ['النرويج', '3–2', 'السنغال'] (1, 3)
71 ['النرويج', '1–4', 'فرنسا'] (1, 3)
72 ['السنغال', '5–0', 'العراق'] (1, 3)
73 ['م', 'الفريقعنت', 'لعب', 'ف', 'ت'] (4, 11)
74 ['الأرجنتين', '3–0', 'الجزائر'] (1, 3)
75 ['النمسا', '3–1', 'الأردن'] (1, 3)
76 ['الأرجنتين', '2–0', 'النمسا'] (1, 3)
77 ['الأردن', '1–2', 'الجزائر'] (1, 3)
78 ['الجزائر', '3–3', 'النمسا'] (1, 3)
79 ['الأردن', '1–3', 'الأرجنتين'] (1, 3)
80 ['م', 'الفريقعنت', 'لعب', 'ف', 'ت'] (4, 11)
81 ['البرتغال', '1–1', 'جمهورية الكونغو الديمقراطية'] (1, 3)
82 ['أوزبكستان', '1–3', 'كولومبيا'] (1, 3)
83 ['البرتغال', '5–0', 'أوزبكستان'] (1, 3)
84 ['كولومبيا', '1–0', 'جمهورية الكونغو الديمقراطية'] (1, 3)
85 ['كولومبيا', '0–0', 'البرتغال'] (1, 3)
86 ['جمهورية الكونغو الديمقراطية', '3–1', 'أوزبكستان'] (1, 3)
87 ['م', 'الفريقعنت', 'لعب', 'ف', 'ت'] (4, 11)
88 ['إنجلترا', '4–2', 'كرواتيا'] (1, 3)
89 ['غانا', '1–0', 'بنما'] (1, 3)
90 ['إنجلترا', '0–0', 'غانا'] (1, 3)
91 ['بنما', '0–1', 'كرواتيا'] (1, 3)
92 ['بنما', '0–2', 'إنجلترا'] (1, 3)
93 ['كرواتيا', '2–1', 'غانا'] (1, 3)
94 ['م', 'مج', 'الفريقعنت', 'لعب', 'ف'] (12, 12)
95 [0, 1, 2, 3, 4] (119, 19)
96 ['جنوب إفريقيا', '0–1', 'كندا'] (1, 3)
97 ['البرازيل', '2–1', 'اليابان'] (1, 3)
98 ['ألمانيا', '1–1 (ب.و.إ.)', 'باراغواي'] (3, 3)
99 ['هولندا', '1–1 (ب.و.إ.)', 'المغرب'] (3, 3)
100 ['ساحل العاج', '1–2', 'النرويج'] (1, 3)
101 ['فرنسا', '3–0', 'السويد'] (1, 3)
102 ['المكسيك', '2–0', 'الإكوادور'] (1, 3)
103 ['إنجلترا', '2–1', 'جمهورية الكونغو الديمقراطية'] (1, 3)
104 ['بلجيكا', '3–2 (ب.و.إ.)', 'السنغال'] (1, 3)
105 ['الولايات المتحدة', '2–0', 'البوسنة والهرسك'] (1, 3)
106 ['إسبانيا', '3–0', 'النمسا'] (1, 3)
107 ['البرتغال', '2–1', 'كرواتيا'] (1, 3)
108 ['سويسرا', '2–0', 'الجزائر'] (1, 3)
109 ['أستراليا', '1–1 (ب.و.إ.)', 'مصر'] (3, 3)
110 ['الأرجنتين', '3–2 (ب.و.إ.)', 'الرأس الأخضر'] (1, 3)
111 ['كولومبيا', '1–0', 'غانا'] (1, 3)
112 ['كندا', '0–3', 'المغرب'] (1, 3)
113 ['باراغواي', '0–1', 'فرنسا'] (1, 3)
114 ['البرازيل', '1–2', 'النرويج'] (1, 3)
115 ['المكسيك', '2–3', 'إنجلترا'] (1, 3)
116 ['البرتغال', '0–1', 'إسبانيا'] (1, 3)
117 ['الولايات المتحدة', '1–4', 'بلجيكا'] (1, 3)
118 ['الأرجنتين', '3–2', 'مصر'] (1, 3)
119 ['سويسرا', '0–0 (ب.و.إ.)', 'كولومبيا'] (3, 3)
120 ['فرنسا', '2–0', 'المغرب'] (1, 3)
121 ['إسبانيا', '2–1', 'بلجيكا'] (1, 3)
122 ['النرويج', '1–2 (ب.و.إ.)', 'إنجلترا'] (1, 3)
123 ['الأرجنتين', '3–1 (ب.و.إ.)', 'سويسرا'] (1, 3)
124 ['فرنسا', '0–2', 'إسبانيا'] (1, 3)
125 ['إنجلترا', '1–2', 'الأرجنتين'] (1, 3)
126 ['فرنسا', '4–6', 'إنجلترا'] (1, 3)
127 ['إسبانيا', '1–0 (ب.و.إ.)', 'الأرجنتين'] (1, 3)
128 ['اللاعب', 'البطاقة', 'الإيقاف'] (14, 3)
129 ['مركز', 'فريق', 'المجموعة', 'لعب', 'ف'] (53, 20)
130 ['الكرة الذهبية', 'الكرة الفضية', 'الكرة البرونزية'] (9, 3)
131 [0, 1, 2] (3, 3)
132 [('المركز', 'المركز'), ('الفرق', 'الفرق'), ('المبلغ (بالمليون دولار أمريكي)', 'لكل فريق'), ('المبلغ (بالمليون دولار أمريكي)', 'الإجمالي')] (9, 4)
133 ['عنتكأس العالم 2026', 'عنتكأس العالم 2026.1'] (4, 2)
134 ['عنتمنتخب النمسا لكرة القدم', 'عنتمنتخب النمسا لكرة القدم.1'] (11, 2)

In [ ]:
stadiums_df = tables[6]
print(stadiums_df.columns.tolist())
stadiums_df.head(20)

['المدينة', 'الملعب', 'عدد المباريات', 'الطاقة الاستيعابية', 'صورة']

,المدينة,الملعب,عدد المباريات,الطاقة الاستيعابية,صورة
0,مدينة مكسيكو,ملعب أزتيكا (ملعب مدينة مكسيكو),5 (3 في مرحلة المجموعات، 2 في مرحلة خروج المغلوب),80،824,NaN
1,نيويورك (شرق راذرفورد),ملعب ميتلايف (ملعب نيويورك نيوجيرسي),8 (5 في مرحلة المجموعات، 2 في مرحلة خروج المغل...,80،663,NaN
2,دالاس (أرلينغتون),ملعب إيه تي آند تي (ملعب دالاس),9 (5 في مرحلة المجموعات، 4 في مرحلة خروج المغلوب),70،649,NaN
3,لوس أنجلوس (إنغلوود),ملعب سوفاي (ملعب لوس أنجلوس),8 (5 في مرحلة المجموعات، 3 في مرحلة خروج المغلوب),70،492,NaN
4,كانساس سيتي,ملعب أروهيد (ملعب كانساس سيتي),6 (4 في مرحلة المجموعات، 2 في مرحلة خروج المغلوب),69،045,NaN
5,سان فرانسيسكو (سانتا كلارا),ملعب ليفاي (ملعب منطقة خليج سان فرانسيسكو),6 (5 في مرحلة المجموعات، 1 في مرحلة خروج المغلوب),68،827,NaN
6,هيوستن,ملعب إن آر جي (ملعب هيوستن),7 (5 في مرحلة المجموعات، 2 في مرحلة خروج المغلوب),68،777,NaN
7,فيلادلفيا,ملعب لينكون فاينانشال فيلد (ملعب فيلادلفيا),6 (5 في مرحلة المجموعات، 1 في مرحلة خروج المغلوب),68،324,NaN
8,أتلانتا,ملعب مرسيدس-بنز (ملعب أتلانتا),8 (5 في مرحلة المجموعات، 3 في مرحلة خروج المغلوب),68،239,NaN
9,سياتل,لومن فيلد (ملعب سياتل),6 (4 في مرحلة المجموعات، 2 في مرحلة خروج المغلوب),66،925,NaN
10,ميامي (ميامي غاردنز),ملعب هارد روك (ملعب ميامي),7 (4 في مرحلة المجموعات، 2 في مرحلة خروج المغل...,64،478,NaN
11,بوسطن (فوكسبورو),ملعب جيليت (ملعب بوسطن),7 (5 في مرحلة المجموعات، 2 في مرحلة خروج المغلوب),64،146,NaN
12,فانكوفر,ملعب بي سي بليس (بي سي بليس فانكوفر),7 (5 في مرحلة المجموعات، 2 في مرحلة خروج المغلوب),52،497,NaN
13,مونتيري (غوادالوبي),ملعب بي بي في إيه (ملعب مونتيري),4 (3 في مرحلة المجموعات، 1 في مرحلة خروج المغلوب),51،243,NaN
14,غوادالاخارا (سابوبان),ملعب أكرون (ملعب غوادالاخارا),4 (4 في مرحلة المجموعات),45،664,NaN
15,تورونتو,ملعب بي إم أو فيلد (ملعب تورونتو),6 (5 في مرحلة المجموعات، 1 في مرحلة خروج المغلوب),43،036,NaN

In [ ]:
big_matches_df = tables[95]
print(big_matches_df.columns.tolist())
big_matches_df.head(10)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18]

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18
0,NaN,دور 32,دور 32,NaN,NaN,دور 16,دور 16,NaN,NaN,ربع النهائي,ربع النهائي,NaN,NaN,نصف النهائي,نصف النهائي,NaN,NaN,النهائي,النهائي
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,29 يونيو – فوكسبورو,29 يونيو – فوكسبورو,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,29 يونيو – فوكسبورو,29 يونيو – فوكسبورو,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,ألمانيا,1 (3),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,ألمانيا,1 (3),NaN,NaN,4 يوليو – فيلادلفيا,4 يوليو – فيلادلفيا,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,باراغواي (ج.),1 (4),NaN,NaN,4 يوليو – فيلادلفيا,4 يوليو – فيلادلفيا,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,باراغواي (ج.),1 (4),NaN,NaN,باراغواي,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,30 يونيو – شرق راذرفورد,30 يونيو – شرق راذرفورد,NaN,NaN,باراغواي,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,30 يونيو – شرق راذرفورد,30 يونيو – شرق راذرفورد,NaN,NaN,فرنسا,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
table_129 = tables[129]
print(table_129.columns.tolist())
table_129.head(10)

['مركز', 'فريق', 'المجموعة', 'لعب', 'ف', 'ت', 'خ', 'نقاط', 'أ.له', 'أ.ع', 'ف.أ', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17', 'Unnamed: 18', 'Unnamed: 19']

,مركز,فريق,المجموعة,لعب,ف,ت,خ,نقاط,أ.له,أ.ع,ف.أ,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19
0,1,إسبانيا,الثامنة,8,7,1,0,22,14,1,+13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,الأرجنتين,العاشرة,8,7,0,1,21,19,8,+11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,خرج من الدور نصف النهائي,خرج من الدور نصف النهائي,خرج من الدور نصف النهائي,خرج من الدور نصف النهائي,خرج من الدور نصف النهائي,خرج من الدور نصف النهائي,خرج من الدور نصف النهائي,خرج من الدور نصف النهائي,خرج من الدور نصف النهائي,خرج من الدور نصف النهائي,خرج من الدور نصف النهائي,خرج من الدور نصف النهائي,خرج من الدور نصف النهائي,خرج من الدور نصف النهائي,خرج من الدور نصف النهائي,خرج من الدور نصف النهائي,خرج من الدور نصف النهائي,خرج من الدور نصف النهائي,خرج من الدور نصف النهائي,خرج من الدور نصف النهائي
3,3,إنجلترا,الثانية عشرة,8,6,1,1,19,20,12,+8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,فرنسا,التاسعة,8,6,0,2,18,20,10,+10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,خرج من ربع النهائي,خرج من ربع النهائي,خرج من ربع النهائي,خرج من ربع النهائي,خرج من ربع النهائي,خرج من ربع النهائي,خرج من ربع النهائي,خرج من ربع النهائي,خرج من ربع النهائي,خرج من ربع النهائي,خرج من ربع النهائي,خرج من ربع النهائي,خرج من ربع النهائي,خرج من ربع النهائي,خرج من ربع النهائي,خرج من ربع النهائي,خرج من ربع النهائي,خرج من ربع النهائي,خرج من ربع النهائي,خرج من ربع النهائي
6,5,النرويج,التاسعة,6,4,0,2,12,13,11,+2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,6,بلجيكا,السابعة,6,3,2,1,11,14,7,+7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,7,المغرب,الثالثة,6,3,2,1,11,10,6,+4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,8,سويسرا,الثانية,6,3,2,1,11,10,6,+4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
group_matches = []

for i in range(11, 94):
    t = tables[i]
    if t.shape == (1, 3):  # المباريات الفردية بس (مش جداول الترتيب)
        row = t.iloc[0]
        group_matches.append({
            "الفريق1": row[0],
            "النتيجة": row[1],
            "الفريق2": row[2],
            "الدور": "دور المجموعات",
            "index_جدول": i
        })

group_df = pd.DataFrame(group_matches)
print(group_df.shape)
group_df.head(20)

(72, 5)

/tmp/ipykernel_9055/2648623266.py:8: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  "الفريق1": row[0],
/tmp/ipykernel_9055/2648623266.py:9: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  "النتيجة": row[1],
/tmp/ipykernel_9055/2648623266.py:10: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  "الفريق2": row[2],

,الفريق1,النتيجة,الفريق2,الدور,index_جدول
0,كينيونيس 9' خيمينيز 67',[تقرير 1],NaN,دور المجموعات,11
1,بيوم 67' هيون جيو 80',[تقرير 2],كريتشي 59',دور المجموعات,12
2,سادلييك 6',[تقرير 3],موكوينا 83' (ر.ج.),دور المجموعات,13
3,رومو 50',[تقرير 4],NaN,دور المجموعات,14
4,NaN,[تقرير 5],م. شافييز 55' كينيونيس 61' فيدالغو 90+4',دور المجموعات,15
5,ماسيكو 63',[تقرير 6],NaN,دور المجموعات,16
6,لارين 78',[تقرير 7],لوكيتش 21',دور المجموعات,18
7,موهايم 4+90' (هـ.ذ.),[تقرير 8],إمبولو 17' (ر.ج.),دور المجموعات,19
8,مانزامبي 74'، 90' فارغاس 84' تشاكا 7+90' (ر.ج.),[تقرير 9],محميتش 90+3',دور المجموعات,20
9,لارين 16' ج. ديفيد 29'، 3+45'، 2+90' صليبا 64'...,[تقرير 10],NaN,دور المجموعات,21
10,فارغاس 46' مانزامبي 57',[تقرير 11],ب. ديفيد 76',دور المجموعات,22
11,ألايبغوفيتش 29' أبو ندى 34' (هـ.ذ.) محميتش 80',[تقرير 12],الهيدوس 42',دور المجموعات,23
12,جونيور 32',[تقرير 13],صيباري 21',دور المجموعات,25
13,NaN,[تقرير 14],مكجين 28',دور المجموعات,26
14,NaN,[تقرير 15],صيباري 2',دور المجموعات,27
15,كونيا 23'، 36' جونيور 3+45',[تقرير 16],NaN,دور المجموعات,28
16,NaN,[تقرير 17],جونيور 7'، 3+45' كونيا 60',دور المجموعات,29
17,حكيمي 39' صيباري 1+45' رحيمي 78' جسيم 89',[تقرير 18],بونو 10' (هـ.ذ.) إيسيدور 43',دور المجموعات,30
18,بوباديلا 7' (هـ.ذ.) بالوغون 31'، 5+45' رينا 8+90',[تقرير 19],ماوريسيو 73',دور المجموعات,32
19,إرانكوندا 27' ميتكالف 75',[تقرير 20],NaN,دور المجموعات,33

In [ ]:
import re

score_pattern = re.compile(r'^\d+\s*[–\-−]\s*\d+')  # نمط زي "7–1" أو "1-0"

group_matches = []
group_scorers = []
match_num = 0

for i in range(11, 94):
    t = tables[i]
    if t.shape != (1, 3):
        continue
    row = t.iloc[0]
    val1 = str(row.iloc[1])  # العمود الأوسط

    if score_pattern.match(val1.strip()):
        # ده جدول نتيجة حقيقي
        match_num += 1
        group_matches.append({
            "رقم_المباراة": match_num,
            "الفريق1": row.iloc[0],
            "النتيجة": row.iloc[1],
            "الفريق2": row.iloc[2],
            "الدور": "دور المجموعات"
        })
    else:
        # ده جدول هدافين تابع لآخر مباراة اتسجلت
        group_scorers.append({
            "رقم_المباراة": match_num,
            "هدافي_الفريق1": row.iloc[0],
            "هدافي_الفريق2": row.iloc[2]
        })

matches_df = pd.DataFrame(group_matches)
scorers_df = pd.DataFrame(group_scorers)

print("عدد المباريات:", matches_df.shape)
print("عدد جداول الهدافين:", scorers_df.shape)
matches_df.head(10)

عدد المباريات: (0, 0)
عدد جداول الهدافين: (72, 3)

Empty DataFrame
Columns: []
Index: []

In [ ]:
scorers_df.head(10)

,رقم_المباراة,هدافي_الفريق1,هدافي_الفريق2
0,0,كينيونيس 9' خيمينيز 67',NaN
1,0,بيوم 67' هيون جيو 80',كريتشي 59'
2,0,سادلييك 6',موكوينا 83' (ر.ج.)
3,0,رومو 50',NaN
4,0,NaN,م. شافييز 55' كينيونيس 61' فيدالغو 90+4'
5,0,ماسيكو 63',NaN
6,0,لارين 78',لوكيتش 21'
7,0,موهايم 4+90' (هـ.ذ.),إمبولو 17' (ر.ج.)
8,0,مانزامبي 74'، 90' فارغاس 84' تشاكا 7+90' (ر.ج.),محميتش 90+3'
9,0,لارين 16' ج. ديفيد 29'، 3+45'، 2+90' صليبا 64'...,NaN

In [ ]:
print(repr(tables[11].columns.tolist()))

['المكسيك', '2–0', 'جنوب إفريقيا']

In [ ]:
import re, unicodedata

def clean_text(s):
    s = str(s)
    s = ''.join(ch for ch in s if unicodedata.category(ch) != 'Cf')
    return s.strip()

score_pattern = re.compile(r'\d+\s*[–\-−]\s*\d+')

group_matches = []
match_num = 0

for i in range(11, 94):
    t = tables[i]
    if t.shape != (1, 3):
        continue
    cols = [clean_text(c) for c in t.columns.tolist()]
    if score_pattern.search(cols[1]):
        match_num += 1
        row = t.iloc[0]
        group_matches.append({
            "رقم_المباراة": match_num,
            "الفريق1": cols[0],
            "النتيجة": cols[1],
            "الفريق2": cols[2],
            "هدافي_الفريق1": row.iloc[0],
            "هدافي_الفريق2": row.iloc[2],
            "الدور": "دور المجموعات",
        })

matches_df = pd.DataFrame(group_matches)
print("عدد المباريات:", matches_df.shape)
matches_df.head(15)

عدد المباريات: (72, 7)

,رقم_المباراة,الفريق1,النتيجة,الفريق2,هدافي_الفريق1,هدافي_الفريق2,الدور
0,1,المكسيك,2–0,جنوب إفريقيا,كينيونيس 9' خيمينيز 67',NaN,دور المجموعات
1,2,كوريا الجنوبية,2–1,التشيك,بيوم 67' هيون جيو 80',كريتشي 59',دور المجموعات
2,3,التشيك,1–1,جنوب إفريقيا,سادلييك 6',موكوينا 83' (ر.ج.),دور المجموعات
3,4,المكسيك,1–0,كوريا الجنوبية,رومو 50',NaN,دور المجموعات
4,5,التشيك,0–3,المكسيك,NaN,م. شافييز 55' كينيونيس 61' فيدالغو 90+4',دور المجموعات
5,6,جنوب إفريقيا,1–0,كوريا الجنوبية,ماسيكو 63',NaN,دور المجموعات
6,7,كندا,1–1,البوسنة والهرسك,لارين 78',لوكيتش 21',دور المجموعات
7,8,قطر,1–1,سويسرا,موهايم 4+90' (هـ.ذ.),إمبولو 17' (ر.ج.),دور المجموعات
8,9,سويسرا,4–1,البوسنة والهرسك,مانزامبي 74'، 90' فارغاس 84' تشاكا 7+90' (ر.ج.),محميتش 90+3',دور المجموعات
9,10,كندا,6–0,قطر,لارين 16' ج. ديفيد 29'، 3+45'، 2+90' صليبا 64'...,NaN,دور المجموعات
10,11,سويسرا,2–1,كندا,فارغاس 46' مانزامبي 57',ب. ديفيد 76',دور المجموعات
11,12,البوسنة والهرسك,3–1,قطر,ألايبغوفيتش 29' أبو ندى 34' (هـ.ذ.) محميتش 80',الهيدوس 42',دور المجموعات
12,13,البرازيل,1–1,المغرب,جونيور 32',صيباري 21',دور المجموعات
13,14,هايتي,0–1,إسكتلندا,NaN,مكجين 28',دور المجموعات
14,15,إسكتلندا,0–1,المغرب,NaN,صيباري 2',دور المجموعات

In [ ]:
knockout_matches = []
ko_match_num = 0

# اسماء الأدوار بالترتيب حسب مكان كل مجموعة مباريات في الجدول
# (هنحطها بسيطة الأول، ونظبطها بعدين لو محتاجة تعديل)
for i in range(96, 128):
    t = tables[i]
    cols = [clean_text(c) for c in t.columns.tolist()]

    if t.shape[0] == 1 and t.shape[1] == 3:
        # مباراة عادية (90 دقيقة أو وقت إضافي بدون ركلات ترجيح)
        if score_pattern.search(cols[1]):
            ko_match_num += 1
            row = t.iloc[0]
            knockout_matches.append({
                "رقم_المباراة": ko_match_num,
                "الفريق1": cols[0],
                "النتيجة": cols[1],
                "الفريق2": cols[2],
                "هدافي_الفريق1": row.iloc[0],
                "هدافي_الفريق2": row.iloc[2],
                "index_جدول": i
            })
    else:
        # مباراة اتحسمت بركلات ترجيح (شكل الجدول مختلف - 3 صفوف)
        knockout_matches.append({
            "رقم_المباراة": None,
            "الفريق1": cols[0] if len(cols) > 0 else None,
            "النتيجة": cols[1] if len(cols) > 1 else None,
            "الفريق2": cols[2] if len(cols) > 2 else None,
            "هدافي_الفريق1": "راجع الجدول يدويًا",
            "هدافي_الفريق2": "راجع الجدول يدويًا",
            "index_جدول": i
        })

knockout_df = pd.DataFrame(knockout_matches)
print(knockout_df.shape)
knockout_df

(32, 7)

,رقم_المباراة,الفريق1,النتيجة,الفريق2,هدافي_الفريق1,هدافي_الفريق2,index_جدول
0,1.0,جنوب إفريقيا,0–1,كندا,NaN,أوستاكيو 2+90',96
1,2.0,البرازيل,2–1,اليابان,كاسيميرو 56' مارتينيلي 5+90',سانو 29',97
2,NaN,ألمانيا,1–1 (ب.و.إ.),باراغواي,راجع الجدول يدويًا,راجع الجدول يدويًا,98
3,NaN,هولندا,1–1 (ب.و.إ.),المغرب,راجع الجدول يدويًا,راجع الجدول يدويًا,99
4,3.0,ساحل العاج,1–2,النرويج,ديالو 74',نوسا 39' هالاند 86',100
5,4.0,فرنسا,3–0,السويد,مبابي 45'، 74' باركولا 53',NaN,101
6,5.0,المكسيك,2–0,الإكوادور,كينيونيس 22' خيمينيز 31',NaN,102
7,6.0,إنجلترا,2–1,جمهورية الكونغو الديمقراطية,كين 75'، 86',سيبنغا 7',103
8,7.0,بلجيكا,3–2 (ب.و.إ.),السنغال,لوكاكو 86' تيليمانس 89'، 5+120' (ر.ج.),ديارا 25' إ. سار 51',104
9,8.0,الولايات المتحدة,2–0,البوسنة والهرسك,بالوغون 45' تيلمان 82',NaN,105
10,9.0,إسبانيا,3–0,النمسا,أويارزابال 36'، 89' بورو 66',NaN,106
11,10.0,البرتغال,2–1,كرواتيا,رونالدو 68' (ر.ج.) راموس 4+90',بيريشيتش 53',107
12,11.0,سويسرا,2–0,الجزائر,إمبولو 10' ندوي 46',NaN,108
13,NaN,أستراليا,1–1 (ب.و.إ.),مصر,راجع الجدول يدويًا,راجع الجدول يدويًا,109
14,12.0,الأرجنتين,3–2 (ب.و.إ.),الرأس الأخضر,ميسي 29' لي. مارتينيز 92' ديني 111' (هـ.ذ.),د. دوارتي 59' لوبيز كابرال 103',110
15,13.0,كولومبيا,1–0,غانا,آرياس 14',NaN,111
16,14.0,كندا,0–3,المغرب,NaN,أوناحي 50'، 82' رحيمي 8+90',112
17,15.0,باراغواي,0–1,فرنسا,NaN,مبابي 70' (ر.ج.),113
18,16.0,البرازيل,1–2,النرويج,نيمار 10+90' (ر.ج.),هالاند 79'، 90',114
19,17.0,المكسيك,2–3,إنجلترا,كينيونيس 42' خيمينيز 69' (ر.ج.),بيلينغهام 36'، 38' كين 60' (ر.ج.),115
20,18.0,البرتغال,0–1,إسبانيا,NaN,ميرينو 1+90',116
21,19.0,الولايات المتحدة,1–4,بلجيكا,تيلمان 31',دي كاتيلايير 9'، 33' فاناكن 57' لوكاكو 3+90',117
22,20.0,الأرجنتين,3–2,مصر,روميرو 79' ميسي 83' فرنانديز 2+90',إبراهيم 15' زيكو 67',118
23,NaN,سويسرا,0–0 (ب.و.إ.),كولومبيا,راجع الجدول يدويًا,راجع الجدول يدويًا,119
24,21.0,فرنسا,2–0,المغرب,مبابي 60' ديمبيلي 66',NaN,120
25,22.0,إسبانيا,2–1,بلجيكا,رويز 30' ميرينو 88',دي كاتيلايير 41',121
26,23.0,النرويج,1–2 (ب.و.إ.),إنجلترا,شييلديروب 36',بيلينغهام 2+45'، 93',122
27,24.0,الأرجنتين,3–1 (ب.و.إ.),سويسرا,ماك أليستير 10' ألفاريز 112' لا. مارتينيز 1+120',ندوي 67',123
28,25.0,فرنسا,0–2,إسبانيا,NaN,أويارزابال 22' (ر.ج.) بورو 58',124
29,26.0,إنجلترا,1–2,الأرجنتين,غوردون 55',فرنانديز 85' لا. مارتينيز 2+90',125
30,27.0,فرنسا,4–6,إنجلترا,مبابي 48'، 66' باركولا 54' ديمبيلي 6+90',رايس 3' كونسا 18' ساكا 37'، 1+45'، 87' (ر.ج.) ...,126
31,28.0,إسبانيا,1–0 (ب.و.إ.),الأرجنتين,توريس 106',NaN,127

In [ ]:
# 1) نشوف شكل الجداول الخاصة بركلات الترجيح الأول
for idx in [98, 99, 109, 119]:
    print(f"--- جدول {idx} ---")
    print(tables[idx].to_string())
    print()

--- جدول 98 ---
                                    ألمانيا   1–1 (ب.و.إ.)                                              باراغواي
0                               هافيرتس 54'     [تقرير 75]                                           إنسيسكو 42'
1                             ركلات الترجيح  ركلات الترجيح                                         ركلات الترجيح
2  هافيرتس كيميش موسيالا فولتماده أميري تاه            3–4  ماوريسيو  غ. غوميز  غلارزا  سانابريا  بالبوينا  كنلي

--- جدول 99 ---
                                       هولندا   1–1 (ب.و.إ.)                                 المغرب
0                                   خاكبو 72'     [تقرير 76]                             ديوب 1+90'
1                               ركلات الترجيح  ركلات الترجيح                          ركلات الترجيح
2  كووبميينيرز كلويفرت فيغورست تيمبير سامرفيل            2–3  العيناوي  رحيمي  طالبي  حكيمي  صيباري

--- جدول 109 ---
                     أستراليا   1–1 (ب.و.إ.)                            مصر
0            هاني 55' (هـ.ذ.)     [تقرير 86]                      عاشور 13'
1               ركلات الترجيح  ركلات الترجيح                  ركلات الترجيح
2  سوتار إرفين مابيل هيرنغتون            2–4  صابر  ربيعة  صلاح  عبد المجيد

--- جدول 119 ---
                            سويسرا   0–0 (ب.و.إ.)                                  كولومبيا
0                              NaN     [تقرير 96]                                       NaN
1                    ركلات الترجيح  ركلات الترجيح                             ركلات الترجيح
2  تشاكا أمدوني أكانجي إيتن فارغاس            4–3  كينتيرو  سانشيز  كامباز  هيرنانديز  دياز

In [ ]:
# أسماء الأدوار بالترتيب - 16 مباراة دور32، 8 دور16، 4 ربع نهائي، 2 نصف نهائي، 1 نهائي = 31
# بس عندنا 32 صف (فيه مباراة تحديد المركز الثالث كمان)
round_names = (
    ["دور الـ32"] * 16 +
    ["دور الـ16"] * 8 +
    ["ربع النهائي"] * 4 +
    ["نصف النهائي"] * 2 +
    ["تحديد المركز الثالث"] * 1 +
    ["النهائي"] * 1
)

penalty_tables = {98, 99, 109, 119}

final_knockout = []
for pos, i in enumerate(range(96, 128)):
    t = tables[i]
    cols = [clean_text(c) for c in t.columns.tolist()]
    dor = round_names[pos] if pos < len(round_names) else "غير معروف"

    if i in penalty_tables:
        row0 = t.iloc[0]  # هدافي الوقت الأصلي
        row2 = t.iloc[2]  # ركلات الترجيح
        final_knockout.append({
            "الفريق1": cols[0],
            "النتيجة": cols[1],
            "الفريق2": cols[2],
            "هدافي_الفريق1": row0.iloc[0],
            "هدافي_الفريق2": row0.iloc[2],
            "ركلات_ترجيح_الفريق1": row2.iloc[0],
            "نتيجة_الركلات": row2.iloc[1],
            "ركلات_ترجيح_الفريق2": row2.iloc[2],
            "الدور": dor
        })
    else:
        row = t.iloc[0]
        final_knockout.append({
            "الفريق1": cols[0],
            "النتيجة": cols[1],
            "الفريق2": cols[2],
            "هدافي_الفريق1": row.iloc[0],
            "هدافي_الفريق2": row.iloc[2],
            "ركلات_ترجيح_الفريق1": None,
            "نتيجة_الركلات": None,
            "ركلات_ترجيح_الفريق2": None,
            "الدور": dor
        })

knockout_final_df = pd.DataFrame(final_knockout)
print(knockout_final_df.shape)
knockout_final_df

(32, 9)

,الفريق1,النتيجة,الفريق2,هدافي_الفريق1,هدافي_الفريق2,ركلات_ترجيح_الفريق1,نتيجة_الركلات,ركلات_ترجيح_الفريق2,الدور
0,جنوب إفريقيا,0–1,كندا,NaN,أوستاكيو 2+90',None,None,None,دور الـ32
1,البرازيل,2–1,اليابان,كاسيميرو 56' مارتينيلي 5+90',سانو 29',None,None,None,دور الـ32
2,ألمانيا,1–1 (ب.و.إ.),باراغواي,هافيرتس 54',إنسيسكو 42',هافيرتس كيميش موسيالا فولتماده أميري تاه,3–4,ماوريسيو غ. غوميز غلارزا سانابريا بالبوينا...,دور الـ32
3,هولندا,1–1 (ب.و.إ.),المغرب,خاكبو 72',ديوب 1+90',كووبميينيرز كلويفرت فيغورست تيمبير سامرفيل,2–3,العيناوي رحيمي طالبي حكيمي صيباري,دور الـ32
4,ساحل العاج,1–2,النرويج,ديالو 74',نوسا 39' هالاند 86',None,None,None,دور الـ32
5,فرنسا,3–0,السويد,مبابي 45'، 74' باركولا 53',NaN,None,None,None,دور الـ32
6,المكسيك,2–0,الإكوادور,كينيونيس 22' خيمينيز 31',NaN,None,None,None,دور الـ32
7,إنجلترا,2–1,جمهورية الكونغو الديمقراطية,كين 75'، 86',سيبنغا 7',None,None,None,دور الـ32
8,بلجيكا,3–2 (ب.و.إ.),السنغال,لوكاكو 86' تيليمانس 89'، 5+120' (ر.ج.),ديارا 25' إ. سار 51',None,None,None,دور الـ32
9,الولايات المتحدة,2–0,البوسنة والهرسك,بالوغون 45' تيلمان 82',NaN,None,None,None,دور الـ32
10,إسبانيا,3–0,النمسا,أويارزابال 36'، 89' بورو 66',NaN,None,None,None,دور الـ32
11,البرتغال,2–1,كرواتيا,رونالدو 68' (ر.ج.) راموس 4+90',بيريشيتش 53',None,None,None,دور الـ32
12,سويسرا,2–0,الجزائر,إمبولو 10' ندوي 46',NaN,None,None,None,دور الـ32
13,أستراليا,1–1 (ب.و.إ.),مصر,هاني 55' (هـ.ذ.),عاشور 13',سوتار إرفين مابيل هيرنغتون,2–4,صابر ربيعة صلاح عبد المجيد,دور الـ32
14,الأرجنتين,3–2 (ب.و.إ.),الرأس الأخضر,ميسي 29' لي. مارتينيز 92' ديني 111' (هـ.ذ.),د. دوارتي 59' لوبيز كابرال 103',None,None,None,دور الـ32
15,كولومبيا,1–0,غانا,آرياس 14',NaN,None,None,None,دور الـ32
16,كندا,0–3,المغرب,NaN,أوناحي 50'، 82' رحيمي 8+90',None,None,None,دور الـ16
17,باراغواي,0–1,فرنسا,NaN,مبابي 70' (ر.ج.),None,None,None,دور الـ16
18,البرازيل,1–2,النرويج,نيمار 10+90' (ر.ج.),هالاند 79'، 90',None,None,None,دور الـ16
19,المكسيك,2–3,إنجلترا,كينيونيس 42' خيمينيز 69' (ر.ج.),بيلينغهام 36'، 38' كين 60' (ر.ج.),None,None,None,دور الـ16
20,البرتغال,0–1,إسبانيا,NaN,ميرينو 1+90',None,None,None,دور الـ16
21,الولايات المتحدة,1–4,بلجيكا,تيلمان 31',دي كاتيلايير 9'، 33' فاناكن 57' لوكاكو 3+90',None,None,None,دور الـ16
22,الأرجنتين,3–2,مصر,روميرو 79' ميسي 83' فرنانديز 2+90',إبراهيم 15' زيكو 67',None,None,None,دور الـ16
23,سويسرا,0–0 (ب.و.إ.),كولومبيا,NaN,NaN,تشاكا أمدوني أكانجي إيتن فارغاس,4–3,كينتيرو سانشيز كامباز هيرنانديز دياز,دور الـ16
24,فرنسا,2–0,المغرب,مبابي 60' ديمبيلي 66',NaN,None,None,None,ربع النهائي
25,إسبانيا,2–1,بلجيكا,رويز 30' ميرينو 88',دي كاتيلايير 41',None,None,None,ربع النهائي
26,النرويج,1–2 (ب.و.إ.),إنجلترا,شييلديروب 36',بيلينغهام 2+45'، 93',None,None,None,ربع النهائي
27,الأرجنتين,3–1 (ب.و.إ.),سويسرا,ماك أليستير 10' ألفاريز 112' لا. مارتينيز 1+120',ندوي 67',None,None,None,ربع النهائي
28,فرنسا,0–2,إسبانيا,NaN,أويارزابال 22' (ر.ج.) بورو 58',None,None,None,نصف النهائي
29,إنجلترا,1–2,الأرجنتين,غوردون 55',فرنانديز 85' لا. مارتينيز 2+90',None,None,None,نصف النهائي
30,فرنسا,4–6,إنجلترا,مبابي 48'، 66' باركولا 54' ديمبيلي 6+90',رايس 3' كونسا 18' ساكا 37'، 1+45'، 87' (ر.ج.) ...,None,None,None,تحديد المركز الثالث
31,إسبانيا,1–0 (ب.و.إ.),الأرجنتين,توريس 106',NaN,None,None,None,النهائي

In [ ]:
# 1) نوحّد أعمدة matches_df (دور المجموعات) عشان تطابق knockout_final_df
matches_df_unified = matches_df.rename(columns={"رقم_المباراة": "رقم_قديم"}).copy()
for col in ["ركلات_ترجيح_الفريق1", "نتيجة_الركلات", "ركلات_ترجيح_الفريق2"]:
    matches_df_unified[col] = None
matches_df_unified = matches_df_unified.drop(columns=["رقم_قديم"])

# 2) ندمج الاتنين في جدول واحد لكل الـ 104 مباراة
all_matches_df = pd.concat([matches_df_unified, knockout_final_df], ignore_index=True)
all_matches_df.insert(0, "رقم_المباراة", range(1, len(all_matches_df) + 1))

print("إجمالي المباريات:", all_matches_df.shape)  # المفروض (104, ...)

# 3) تنظيف جدول الملاعب
stadiums_clean = stadiums_df.copy()
stadiums_clean["الطاقة الاستيعابية"] = (
    stadiums_clean["الطاقة الاستيعابية"].astype(str)
    .str.replace("،", "", regex=False)
    .str.extract(r"(\d+)")[0]
    .astype(int)
)
stadiums_clean["عدد المباريات"] = (
    stadiums_clean["عدد المباريات"].astype(str)
    .str.extract(r"^(\d+)")[0]
    .astype(int)
)
stadiums_clean = stadiums_clean.drop(columns=["صورة"])

print("الملاعب:")
print(stadiums_clean)

# 4) تصدير الملفات
all_matches_df.to_csv("world_cup_2026_matches.csv", index=False, encoding="utf-8-sig")
stadiums_clean.to_csv("world_cup_2026_stadiums.csv", index=False, encoding="utf-8-sig")

from google.colab import files
files.download("world_cup_2026_matches.csv")
files.download("world_cup_2026_stadiums.csv")

إجمالي المباريات: (104, 10)
الملاعب:
                        المدينة                                       الملعب  \
0                  مدينة مكسيكو              ملعب أزتيكا (ملعب مدينة مكسيكو)
1        نيويورك (شرق راذرفورد)         ملعب ميتلايف (ملعب نيويورك نيوجيرسي)
2             دالاس (أرلينغتون)              ملعب إيه تي آند تي (ملعب دالاس)
3          لوس أنجلوس (إنغلوود)                 ملعب سوفاي (ملعب لوس أنجلوس)
4                   كانساس سيتي               ملعب أروهيد (ملعب كانساس سيتي)
5   سان فرانسيسكو (سانتا كلارا)   ملعب ليفاي (ملعب منطقة خليج سان فرانسيسكو)
6                        هيوستن                  ملعب إن آر جي (ملعب هيوستن)
7                     فيلادلفيا  ملعب لينكون فاينانشال فيلد (ملعب فيلادلفيا)
8                       أتلانتا               ملعب مرسيدس-بنز (ملعب أتلانتا)
9                         سياتل                       لومن فيلد (ملعب سياتل)
10         ميامي (ميامي غاردنز)                   ملعب هارد روك (ملعب ميامي)
11             بوسطن (فوكسبورو)                      ملعب جيليت (ملعب بوسطن)
12                      فانكوفر         ملعب بي سي بليس (بي سي بليس فانكوفر)
13          مونتيري (غوادالوبي)             ملعب بي بي في إيه (ملعب مونتيري)
14        غوادالاخارا (سابوبان)                ملعب أكرون (ملعب غوادالاخارا)
15                      تورونتو            ملعب بي إم أو فيلد (ملعب تورونتو)

    عدد المباريات  الطاقة الاستيعابية
0               5               80824
1               8               80663
2               9               70649
3               8               70492
4               6               69045
5               6               68827
6               7               68777
7               6               68324
8               8               68239
9               6               66925
10              7               64478
11              7               64146
12              7               52497
13              4               51243
14              4               45664
15              6               43036

In [ ]:
import re

def parse_scorers(text, team, match_id):
    if pd.isna(text):
        return []
    text = str(text).replace('\xa0', ' ')
    pattern = re.compile(r'([\u0600-\u06FF][\u0600-\u06FF\.\s]*?)\s*((?:\d+(?:\+\d+)?\'(?:\s*\([^)]*\))?(?:\s*،\s*)?)+)')
    results = []
    for name, times_blob in pattern.findall(text):
        name = name.strip()
        own_goal = 'هـ.ذ.' in times_blob
        is_penalty = 'ر.ج.' in times_blob
        times = re.findall(r"\d+(?:\+\d+)?'", times_blob)
        for t in times:
            results.append({
                "رقم_المباراة": match_id,
                "اللاعب": name,
                "الفريق_المستفيد": team,
                "الدقيقة": t,
                "هدف_عكسي": own_goal,
            })
    return results

all_scorers = []
for _, row in all_matches_df.iterrows():
    all_scorers += parse_scorers(row["هدافي_الفريق1"], row["الفريق1"], row["رقم_المباراة"])
    all_scorers += parse_scorers(row["هدافي_الفريق2"], row["الفريق2"], row["رقم_المباراة"])

scorers_df = pd.DataFrame(all_scorers)
print("إجمالي الأهداف المستخرجة:", scorers_df.shape)

# ترتيب الهدافين (نستبعد الأهداف العكسية لأنها مش لصالح لاعب الفريق)
top_scorers = (
    scorers_df[~scorers_df["هدف_عكسي"]]
    .groupby("اللاعب")
    .size()
    .reset_index(name="عدد_الأهداف")
    .sort_values("عدد_الأهداف", ascending=False)
    .reset_index(drop=True)
)

print(top_scorers.head(15))

# تصدير
scorers_df.to_csv("world_cup_2026_all_goals.csv", index=False, encoding="utf-8-sig")
top_scorers.to_csv("world_cup_2026_top_scorers.csv", index=False, encoding="utf-8-sig")

from google.colab import files
files.download("world_cup_2026_all_goals.csv")
files.download("world_cup_2026_top_scorers.csv")

إجمالي الأهداف المستخرجة: (308, 5)
        اللاعب  عدد_الأهداف
0        مبابي           10
1         ميسي            8
2    بيلينغهام            7
3       هالاند            7
4      ديمبيلي            6
5          كين            6
6   أويارزابال            5
7       جونيور            4
8     كينيونيس            4
9         جاست            3
10    ج. ديفيد            3
11      صيباري            3
12        ساكا            3
13         سار            3
14       خاكبو            3

In [ ]:
from bs4 import BeautifulSoup

soup = BeautifulSoup(response.text, "lxml")
football_boxes = soup.find_all("div", class_="footballbox")
print("عدد الصناديق اللي لقيناها:", len(football_boxes))

# نطبع أول صندوقين كاملين عشان نشوف الشكل
for box in football_boxes[:2]:
    print("=" * 60)
    print(box.prettify()[:3000])

عدد الصناديق اللي لقيناها: 104
============================================================
<div about="#mwt478" class="footballbox" itemscope="" itemtype="http://schema.org/SportsEvent" style="color:inherit">
 <div class="fright">
  <time>
   <div class="fdate">
    11
    <span typeof="mw:Entity">
    </span>
    يونيو
    <span typeof="mw:Entity">
    </span>
    2026
    <span style="display:none">
     <span typeof="mw:Entity">
     </span>
     (
     <span class="bday dtstart published updated">
      2026-06-11
     </span>
     )
    </span>
   </div>
   <div class="ftime">
    1:00
    <span typeof="mw:Entity">
    </span>
    م
    <a href="https://ar.wikipedia.org/wiki/ت_ع_م−06:00" rel="mw:WikiLink" title="ت ع م−06:00">
     ت ع م−06:00
    </a>
   </div>
  </time>
 </div>
 <table class="fevent">
  <tbody>
   <tr itemprop="name">
    <th class="fhome" itemprop="homeTeam" itemscope="" itemtype="http://schema.org/SportsTeam">
     <span itemprop="name">
      <a href="https://ar.wikipedia.org/wiki/منتخب_المكسيك_لكرة_القدم" rel="mw:WikiLink" title="منتخب المكسيك لكرة القدم">
       المكسيك
      </a>
      <span class="flagicon">
       <span typeof="mw:Entity">
       </span>
       <span class="mw-image-border" typeof="mw:File">
        <span>
         <img alt="" class="mw-file-element" data-file-height="560" data-file-type="drawing" data-file-width="980" decoding="async" height="13" loading="lazy" resource="https://ar.wikipedia.org/wiki/ملف:Flag_of_Mexico.svg" src="//upload.wikimedia.org/wikipedia/commons/thumb/f/fc/Flag_of_Mexico.svg/40px-Flag_of_Mexico.svg.png?utm_source=ar.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/f/fc/Flag_of_Mexico.svg/60px-Flag_of_Mexico.svg.png?utm_source=ar.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="23"/>
        </span>
       </span>
      </span>
     </span>
    </th>
    <th class="fscore">
     <a href="https://ar.wikipedia.org/wiki/كأس_العالم_2026_المجموعة_الأولى#المكسيك_ضد_جنوب_إفريقيا" rel="mw:WikiLink" title="كأس العالم 2026 المجموعة الأولى">
      2–0
     </a>
    </th>
    <th class="faway" itemprop="awayTeam" itemscope="" itemtype="http://schema.org/SportsTeam">
     <span itemprop="name">
      <span class="flagicon">
       <span class="mw-image-border" typeof="mw:File">
        <span>
         <img alt="" class="mw-file-element" data-file-height="600" data-file-type="drawing" data-file-width="900" decoding="async" height="15" loading="lazy" resource="https://ar.wikipedia.org/wiki/ملف:Flag_of_South_Africa.svg" src="//upload.wikimedia.org/wikipedia/commons/thumb/a/af/Flag_of_South_Africa.svg/40px-Flag_of_South_Africa.svg.png?utm_source=ar.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/a/af/Flag_of_South_Africa.svg/60px-Flag_of_South_Africa.svg.png?utm_source=ar.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="23"/>
        </span>
       </span>
       <span typeof="mw:Entity">

============================================================
<div about="#mwt485" class="footballbox" itemscope="" itemtype="http://schema.org/SportsEvent" style="color:inherit">
 <div class="fright">
  <time>
   <div class="fdate">
    11
    <span typeof="mw:Entity">
    </span>
    يونيو
    <span typeof="mw:Entity">
    </span>
    2026
    <span style="display:none">
     <span typeof="mw:Entity">
     </span>
     (
     <span class="bday dtstart published updated">
      2026-06-11
     </span>
     )
    </span>
   </div>
   <div class="ftime">
    8:00
    <span typeof="mw:Entity">
    </span>
    م
    <a href="https://ar.wikipedia.org/wiki/ت_ع_م−06:00" rel="mw:WikiLink" title="ت ع م−06:00">
     ت ع م−06:00
    </a>
   </div>
  </time>
 </div>
 <table class="fevent">
  <tbody>
   <tr itemprop="name">
    <th class="fhome" itemprop="homeTeam" itemscope="" itemtype="http://schema.org/SportsTeam">
     <span itemprop="name">
      <a href="https://ar.wikipedia.org/wiki/منتخب_كوريا_الجنوبية_لكرة_القدم" rel="mw:WikiLink" title="منتخب كوريا الجنوبية لكرة القدم">
       كوريا الجنوبية
      </a>
      <span class="flagicon">
       <span typeof="mw:Entity">
       </span>
       <span class="mw-image-border" typeof="mw:File">
        <span>
         <img alt="" class="mw-file-element" data-file-height="600" data-file-type="drawing" data-file-width="900" decoding="async" height="15" loading="lazy" resource="https://ar.wikipedia.org/wiki/ملف:Flag_of_South_Korea.svg" src="//upload.wikimedia.org/wikipedia/commons/thumb/0/09/Flag_of_South_Korea.svg/40px-Flag_of_South_Korea.svg.png?utm_source=ar.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/0/09/Flag_of_South_Korea.svg/60px-Flag_of_South_Korea.svg.png?utm_source=ar.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail 2x" width="23"/>
        </span>
       </span>
      </span>
     </span>
    </th>
    <th class="fscore">
     <a href="https://ar.wikipedia.org/wiki/كأس_العالم_2026_المجموعة_الأولى#كوريا_الجنوبية_ضد_جمهورية_التشيك" rel="mw:WikiLink" title="كأس العالم 2026 المجموعة الأولى">
      2–1
     </a>
    </th>
    <th class="faway" itemprop="awayTeam" itemscope="" itemtype="http://schema.org/SportsTeam">
     <span itemprop="name">
      <span class="flagicon">
       <span class="mw-image-border" typeof="mw:File">
        <span>
         <img alt="" class="mw-file-element" data-file-height="600" data-file-type="drawing" data-file-width="900" decoding="async" height="15" loading="lazy" resource="https://ar.wikipedia.org/wiki/ملف:Flag_of_the_Czech_Republic.svg" src="//upload.wikimedia.org/wikipedia/commons/thumb/c/cb/Flag_of_the_Czech_Republic.svg/40px-Flag_of_the_Czech_Republic.svg.png?utm_source=ar.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbnail" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/c/cb/Flag_of_the_Czech_Republic.svg/60px-Flag_of_the_Czech_Republic.svg.png?utm_source=ar.wikipedia.org&amp;utm_campaign=parser&amp;utm_content=thumbna

In [ ]:
box_text = football_boxes[0].get_text(separator=" | ", strip=True)
print(box_text)

11 | يونيو | 2026 | ( | 2026-06-11 | ) | 1:00 | م | ت ع م−06:00 | المكسيك | 2–0 | جنوب إفريقيا | كينيونيس | 9' | خيمينيز | 67' | [ | تقرير 1 | ] | ملعب أزتيكا | ، | مدينة مكسيكو | الحضور: 80,824 | الحكم: | ويلتون سامبايو | ( | البرازيل | )

In [ ]:
import re

def parse_box(box, i):
    bday = box.find("span", class_="bday")
    date = bday.get_text(strip=True) if bday else None

    ftime = box.find("div", class_="ftime")
    time_ = ftime.get_text(strip=True) if ftime else None

    full_text = box.get_text(separator=" ", strip=True)

    m = re.search(
        r'ملعب\s+(.+?)،\s*(.+?)\s+الحضور:\s*([\d,]+)\s+الحكم:\s*(.+?)\s*\(\s*(.+?)\s*\)',
        full_text
    )
    if m:
        stadium, city, attendance, referee, referee_country = m.groups()
        attendance = attendance.replace(",", "")
    else:
        stadium, city, attendance, referee, referee_country = [None]*5

    return {
        "رقم_المباراة": i + 1,
        "التاريخ": date,
        "الوقت": time_,
        "الملعب": stadium,
        "المدينة": city,
        "الحضور": attendance,
        "الحكم": referee,
        "بلد_الحكم": referee_country,
    }

match_details = [parse_box(box, i) for i, box in enumerate(football_boxes)]
match_details_df = pd.DataFrame(match_details)

print(match_details_df.shape)
print("عدد الصفوف الناقصة:", match_details_df["الملعب"].isna().sum())
match_details_df.head(10)

(104, 8)
عدد الصفوف الناقصة: 60

,رقم_المباراة,التاريخ,الوقت,الملعب,المدينة,الحضور,الحكم,بلد_الحكم
0,1,2026-06-11,1:00مت ع م−06:00,أزتيكا,مدينة مكسيكو,80824,ويلتون سامبايو,البرازيل
1,2,2026-06-11,8:00مت ع م−06:00,أكرون,سابوبان,44985,أمين عمر,مصر
2,3,2026-06-18,12:00مت ع م-04:00,مرسيدس-بنز,أتلانتا,67442,توري بينسو,الولايات المتحدة
3,4,2026-06-18,7:00مت ع م−06:00,أكرون,سابوبان,45522,غوستافو تيجيرا,أوروغواي
4,5,2026-06-24,7:00مت ع م−06:00,أزتيكا,مدينة مكسيكو,80824,يائيل فالكون,الأرجنتين
5,6,2026-06-24,7:00مت ع م−06:00,بي بي في إيه,غوادالوبي,51243,فاكوندو تيلو,الأرجنتين
6,7,2026-06-12,3:00مت.ع.م−4,بي إم أو فيلد,تورونتو,43002,فاكوندو تيلو,الأرجنتين
7,8,2026-06-13,12:00مت.ع.م−7,None,None,None,None,None
8,9,2026-06-18,12:00مت.ع.م−7,سوفاي,إنغلوود,70026,جواو بينهيرو,البرتغال
9,10,2026-06-18,3:00مت.ع.م−7,None,None,None,None,None

In [ ]:
print(football_boxes[7].get_text(separator=" ", strip=True))

13 يونيو 2026 ( 2026-06-13 ) 12:00 م ت.ع.م−7 قطر 1–1 سويسرا موهايم 4+90' ( هـ.ذ. ) [ تقرير 8 ] إمبولو 17' ( ر.ج. ) ملعب ليفاي ، سانتا كلارا الحضور: 67،966 الحكم: سعيد مارتينيز ( هندوراس )

In [ ]:
import re

def parse_box(box, i):
    bday = box.find("span", class_="bday")
    date = bday.get_text(strip=True) if bday else None

    ftime = box.find("div", class_="ftime")
    time_ = ftime.get_text(strip=True) if ftime else None

    full_text = box.get_text(separator=" ", strip=True)

    m = re.search(
        r'ملعب\s+(.+?)،\s*(.+?)\s+الحضور:\s*([\d,،]+)\s+الحكم:\s*(.+?)\s*\(\s*(.+?)\s*\)',
        full_text
    )
    if m:
        stadium, city, attendance, referee, referee_country = m.groups()
        attendance = attendance.replace(",", "").replace("،", "")
    else:
        stadium, city, attendance, referee, referee_country = [None]*5

    return {
        "رقم_المباراة": i + 1,
        "التاريخ": date,
        "الوقت": time_,
        "الملعب": stadium,
        "المدينة": city,
        "الحضور": attendance,
        "الحكم": referee,
        "بلد_الحكم": referee_country,
    }

match_details = [parse_box(box, i) for i, box in enumerate(football_boxes)]
match_details_df = pd.DataFrame(match_details)

print(match_details_df.shape)
print("عدد الصفوف الناقصة:", match_details_df["الملعب"].isna().sum())
match_details_df.head(10)

(104, 8)
عدد الصفوف الناقصة: 5

,رقم_المباراة,التاريخ,الوقت,الملعب,المدينة,الحضور,الحكم,بلد_الحكم
0,1,2026-06-11,1:00مت ع م−06:00,أزتيكا,مدينة مكسيكو,80824,ويلتون سامبايو,البرازيل
1,2,2026-06-11,8:00مت ع م−06:00,أكرون,سابوبان,44985,أمين عمر,مصر
2,3,2026-06-18,12:00مت ع م-04:00,مرسيدس-بنز,أتلانتا,67442,توري بينسو,الولايات المتحدة
3,4,2026-06-18,7:00مت ع م−06:00,أكرون,سابوبان,45522,غوستافو تيجيرا,أوروغواي
4,5,2026-06-24,7:00مت ع م−06:00,أزتيكا,مدينة مكسيكو,80824,يائيل فالكون,الأرجنتين
5,6,2026-06-24,7:00مت ع م−06:00,بي بي في إيه,غوادالوبي,51243,فاكوندو تيلو,الأرجنتين
6,7,2026-06-12,3:00مت.ع.م−4,بي إم أو فيلد,تورونتو,43002,فاكوندو تيلو,الأرجنتين
7,8,2026-06-13,12:00مت.ع.م−7,ليفاي,سانتا كلارا,67966,سعيد مارتينيز,هندوراس
8,9,2026-06-18,12:00مت.ع.م−7,سوفاي,إنغلوود,70026,جواو بينهيرو,البرتغال
9,10,2026-06-18,3:00مت.ع.م−7,بي سي بليس,فانكوفر,52497,كريستيان غاراي,تشيلي

In [ ]:
missing_indices = match_details_df[match_details_df["الملعب"].isna()].index.tolist()
print("أرقام المباريات الناقصة:", [i+1 for i in missing_indices])

for idx in missing_indices:
    print("=" * 60)
    print(f"مباراة رقم {idx+1}:")
    print(football_boxes[idx].get_text(separator=" ", strip=True))

أرقام المباريات الناقصة: [12, 21, 37, 41, 94]
============================================================
مباراة رقم 12:
24 يونيو 2026 ( 2026-06-24 ) 12:00 م ت.ع.م−7 البوسنة والهرسك 3–1 قطر ألايبغوفيتش 29' أبو ندى 34' ( هـ.ذ. ) محميتش 80' [ تقرير 12 ] الهيدوس 42' لومن فيلد ، سياتل الحضور: 66,925 الحكم: خيسوس فالنزويلا ( فنزويلا )
============================================================
مباراة رقم 21:
19 يونيو 2026 ( 2026-06-19 ) 12:00 م ت.ع.م−7 الولايات المتحدة 2–0 أستراليا بورغس 11' ( هـ.ذ. ) فريمان 43' [ تقرير 21 ] لومن فيلد ، سياتل الحضور: 66,925 الحكم: فيليكس تسفاير ( ألمانيا )
============================================================
مباراة رقم 37:
15 يونيو 2026 ( 2026-06-15 ) 12:00 م ت.ع.م−7 بلجيكا 1–1 مصر هاني 66' ( هـ.ذ. ) [ تقرير 37 ] عاشور 19' لومن فيلد ، سياتل الحضور: 66,775 الحكم: رامون أباتي ( البرازيل )
============================================================
مباراة رقم 41:
26 يونيو 2026 ( 2026-06-26 ) 8:00 م ت.ع.م−7 مصر 1–1 إيران صابر 5' [ تقرير 41 ] رضائيان 14' لومن فيلد ، سياتل الحضور: 66,925 الحكم: شيمون مارتشينياك ( بولندا )
============================================================
مباراة رقم 94:
6 يوليو 2026 ( 2026-07-06 ) 5:00 م ت.ع.م−7 الولايات المتحدة 1–4 بلجيكا تيلمان 31' [ تقرير 94 ] دي كاتيلايير 9' ، 33' فاناكن 57' لوكاكو 3+90' لومن فيلد ، سياتل الحضور: 66،925 الحكم: أدهم مخادمة ( الأردن )

In [ ]:
import re

def parse_box(box, i):
    bday = box.find("span", class_="bday")
    date = bday.get_text(strip=True) if bday else None

    ftime = box.find("div", class_="ftime")
    time_ = ftime.get_text(strip=True) if ftime else None

    full_text = box.get_text(separator=" ", strip=True)

    # لاحظ: خليت الجزء الأول (.+) بدون علامة استفهام (غير كسول/greedy)
    # عشان يمسك آخر فاصلة قبل المدينة، مش أول فاصلة يلاقيها في النص
    m = re.search(
        r'(.+)،\s*(.+?)\s+الحضور:\s*([\d,،]+)\s+الحكم:\s*(.+?)\s*\(\s*(.+?)\s*\)',
        full_text
    )
    if m:
        stadium, city, attendance, referee, referee_country = m.groups()
        stadium = re.sub(r'^ملعب\s+', '', stadium).strip()  # نشيل كلمة "ملعب" لو موجودة في الأول
        attendance = attendance.replace(",", "").replace("،", "")
    else:
        stadium, city, attendance, referee, referee_country = [None]*5

    return {
        "رقم_المباراة": i + 1,
        "التاريخ": date,
        "الوقت": time_,
        "الملعب": stadium,
        "المدينة": city,
        "الحضور": attendance,
        "الحكم": referee,
        "بلد_الحكم": referee_country,
    }

match_details = [parse_box(box, i) for i, box in enumerate(football_boxes)]
match_details_df = pd.DataFrame(match_details)

print(match_details_df.shape)
print("عدد الصفوف الناقصة:", match_details_df["الملعب"].isna().sum())
match_details_df[match_details_df["رقم_المباراة"].isin([12,21,37,41,94])]

(104, 8)
عدد الصفوف الناقصة: 0

,رقم_المباراة,التاريخ,الوقت,الملعب,المدينة,الحضور,الحكم,بلد_الحكم
11,12,2026-06-24,12:00مت.ع.م−7,24 يونيو 2026 ( 2026-06-24 ) 12:00 م ت.ع.م−7 ا...,سياتل,66925,خيسوس فالنزويلا,فنزويلا
20,21,2026-06-19,12:00مت.ع.م−7,19 يونيو 2026 ( 2026-06-19 ) 12:00 م ت.ع.م−7 ا...,سياتل,66925,فيليكس تسفاير,ألمانيا
36,37,2026-06-15,12:00مت.ع.م−7,15 يونيو 2026 ( 2026-06-15 ) 12:00 م ت.ع.م−7 ب...,سياتل,66775,رامون أباتي,البرازيل
40,41,2026-06-26,8:00مت.ع.م−7,26 يونيو 2026 ( 2026-06-26 ) 8:00 م ت.ع.م−7 مص...,سياتل,66925,شيمون مارتشينياك,بولندا
93,94,2026-07-06,5:00مت.ع.م−7,6 يوليو 2026 ( 2026-07-06 ) 5:00 م ت.ع.م−7 الو...,سياتل,66925,أدهم مخادمة,الأردن

In [ ]:
import re

def parse_box(box, i):
    bday = box.find("span", class_="bday")
    date = bday.get_text(strip=True) if bday else None

    ftime = box.find("div", class_="ftime")
    time_ = ftime.get_text(strip=True) if ftime else None

    full_text = box.get_text(separator=" ", strip=True)

    # [^\d\[\]']+  يعني: أي حروف من غير أرقام أو أقواس مربعة أو علامة '
    # ده بيمنع الـ regex إنه "يرجع لورا" فوق أوقات الأهداف زي 42' أو روابط زي [ تقرير 12 ]
    m = re.search(
        r"([^\d\[\]']+?)،\s*(.+?)\s+الحضور:\s*([\d,،]+)\s+الحكم:\s*(.+?)\s*\(\s*(.+?)\s*\)",
        full_text
    )
    if m:
        stadium, city, attendance, referee, referee_country = m.groups()
        stadium = re.sub(r'^ملعب\s+', '', stadium).strip()
        attendance = attendance.replace(",", "").replace("،", "")
    else:
        stadium, city, attendance, referee, referee_country = [None]*5

    return {
        "رقم_المباراة": i + 1,
        "التاريخ": date,
        "الوقت": time_,
        "الملعب": stadium,
        "المدينة": city,
        "الحضور": attendance,
        "الحكم": referee,
        "بلد_الحكم": referee_country,
    }

match_details = [parse_box(box, i) for i, box in enumerate(football_boxes)]
match_details_df = pd.DataFrame(match_details)

print(match_details_df.shape)
print("عدد الصفوف الناقصة:", match_details_df["الملعب"].isna().sum())

# تحقق مباشر: هل أطول اسم في عمود الملعب معقول (أقل من 30 حرف) ولا لسه فيه نص طويل ملخبط؟
print("أطول قيمة في عمود الملعب:", match_details_df["الملعب"].str.len().max())

match_details_df.head(10)

(104, 8)
عدد الصفوف الناقصة: 0
أطول قيمة في عمود الملعب: 58

,رقم_المباراة,التاريخ,الوقت,الملعب,المدينة,الحضور,الحكم,بلد_الحكم
0,1,2026-06-11,1:00مت ع م−06:00,ملعب أزتيكا,مدينة مكسيكو,80824,ويلتون سامبايو,البرازيل
1,2,2026-06-11,8:00مت ع م−06:00,ملعب أكرون,سابوبان,44985,أمين عمر,مصر
2,3,2026-06-18,12:00مت ع م-04:00,( ر.ج. ) ملعب مرسيدس-بنز,أتلانتا,67442,توري بينسو,الولايات المتحدة
3,4,2026-06-18,7:00مت ع م−06:00,ملعب أكرون,سابوبان,45522,غوستافو تيجيرا,أوروغواي
4,5,2026-06-24,7:00مت ع م−06:00,ملعب أزتيكا,مدينة مكسيكو,80824,يائيل فالكون,الأرجنتين
5,6,2026-06-24,7:00مت ع م−06:00,ملعب بي بي في إيه,غوادالوبي,51243,فاكوندو تيلو,الأرجنتين
6,7,2026-06-12,3:00مت.ع.م−4,ملعب بي إم أو فيلد,تورونتو,43002,فاكوندو تيلو,الأرجنتين
7,8,2026-06-13,12:00مت.ع.م−7,( ر.ج. ) ملعب ليفاي,سانتا كلارا,67966,سعيد مارتينيز,هندوراس
8,9,2026-06-18,12:00مت.ع.م−7,,90' فارغاس 84' تشاكا 7+90' ( ر.ج. ) [ تقرير 9 ...,70026,جواو بينهيرو,البرتغال
9,10,2026-06-18,3:00مت.ع.م−7,,3+45' ، 2+90' صليبا 64' المناعي 75' ( هـ.ذ. ) ...,52497,كريستيان غاراي,تشيلي

In [ ]:
print(football_boxes[8].get_text(separator=" ", strip=True))

18 يونيو 2026 ( 2026-06-18 ) 12:00 م ت.ع.م−7 سويسرا 4–1 البوسنة والهرسك مانزامبي 74' ، 90' فارغاس 84' تشاكا 7+90' ( ر.ج. ) [ تقرير 9 ] محميتش 90+3' ملعب سوفاي ، إنغلوود الحضور: 70,026 الحكم: جواو بينهيرو ( البرتغال )

In [ ]:
import re

def parse_box(box, i):
    bday = box.find("span", class_="bday")
    date = bday.get_text(strip=True) if bday else None

    ftime = box.find("div", class_="ftime")
    time_ = ftime.get_text(strip=True) if ftime else None

    full_text = box.get_text(separator=" ", strip=True)

    # ضفت الأقواس () لقائمة الاستبعاد، وضفت \s كحرف مسموح صراحة
    m = re.search(
        r"([^\d\[\]'()]+?)،\s*(.+?)\s+الحضور:\s*([\d,،]+)\s+الحكم:\s*(.+?)\s*\(\s*(.+?)\s*\)",
        full_text
    )
    if m:
        stadium, city, attendance, referee, referee_country = m.groups()
        stadium = re.sub(r'^ملعب\s+', '', stadium).strip()
        attendance = attendance.replace(",", "").replace("،", "")
    else:
        stadium, city, attendance, referee, referee_country = [None]*5

    return {
        "رقم_المباراة": i + 1,
        "التاريخ": date,
        "الوقت": time_,
        "الملعب": stadium,
        "المدينة": city,
        "الحضور": attendance,
        "الحكم": referee,
        "بلد_الحكم": referee_country,
    }

match_details = [parse_box(box, i) for i, box in enumerate(football_boxes)]
match_details_df = pd.DataFrame(match_details)

print(match_details_df.shape)
print("عدد الصفوف الناقصة أو الفاضية:", (match_details_df["الملعب"].isna() | (match_details_df["الملعب"] == "")).sum())
print("أطول قيمة في عمود الملعب:", match_details_df["الملعب"].str.len().max())
match_details_df.iloc[[2,7,8,9]]

(104, 8)
عدد الصفوف الناقصة أو الفاضية: 36
أطول قيمة في عمود الملعب: 58

,رقم_المباراة,التاريخ,الوقت,الملعب,المدينة,الحضور,الحكم,بلد_الحكم
2,3,2026-06-18,12:00مت ع م-04:00,ملعب مرسيدس-بنز,أتلانتا,67442,توري بينسو,الولايات المتحدة
7,8,2026-06-13,12:00مت.ع.م−7,ملعب ليفاي,سانتا كلارا,67966,سعيد مارتينيز,هندوراس
8,9,2026-06-18,12:00مت.ع.م−7,,90' فارغاس 84' تشاكا 7+90' ( ر.ج. ) [ تقرير 9 ...,70026,جواو بينهيرو,البرتغال
9,10,2026-06-18,3:00مت.ع.م−7,,3+45' ، 2+90' صليبا 64' المناعي 75' ( هـ.ذ. ) ...,52497,كريستيان غاراي,تشيلي

In [ ]:
import re

def parse_box(box, i):
    bday = box.find("span", class_="bday")
    date = bday.get_text(strip=True) if bday else None

    ftime = box.find("div", class_="ftime")
    time_ = ftime.get_text(strip=True) if ftime else None

    full_text = box.get_text(separator=" ", strip=True)

    stadium = city = attendance = referee = referee_country = None

    idx_att = full_text.find("الحضور:")
    if idx_att != -1:
        before_att = full_text[:idx_att].strip()

        # آخر فاصلة عربية قبل "الحضور:" هي دايمًا اللي بتفصل الملعب عن المدينة
        last_comma = before_att.rfind("،")
        if last_comma != -1:
            venue_part = before_att[:last_comma]
            city = before_att[last_comma + 1:].strip()

            # نمسك بس آخر جزء من venue_part اللي مفيهوش أرقام/أقواس/علامة تنصيص
            # (عشان نستبعد أوقات الأهداف اللي ممكن تكون قبل اسم الملعب مباشرة)
            m_stadium = re.search(r"([^\d\[\]'()]+)$", venue_part)
            if m_stadium:
                stadium = re.sub(r'^ملعب\s+', '', m_stadium.group(1).strip()).strip()

        rest = full_text[idx_att:]
        m_att = re.search(r'الحضور:\s*([\d,،]+)', rest)
        if m_att:
            attendance = m_att.group(1).replace(",", "").replace("،", "")

        m_ref = re.search(r'الحكم:\s*(.+?)\s*\(\s*(.+?)\s*\)', rest)
        if m_ref:
            referee, referee_country = m_ref.group(1).strip(), m_ref.group(2).strip()

    return {
        "رقم_المباراة": i + 1,
        "التاريخ": date,
        "الوقت": time_,
        "الملعب": stadium,
        "المدينة": city,
        "الحضور": attendance,
        "الحكم": referee,
        "بلد_الحكم": referee_country,
    }

match_details = [parse_box(box, i) for i, box in enumerate(football_boxes)]
match_details_df = pd.DataFrame(match_details)

print(match_details_df.shape)
print("عدد الصفوف الناقصة أو الفاضية:", (match_details_df["الملعب"].isna() | (match_details_df["الملعب"] == "")).sum())
print("أطول قيمة في عمود الملعب:", match_details_df["الملعب"].str.len().max())
print()
print(sorted(match_details_df["الملعب"].unique()))

(104, 8)
عدد الصفوف الناقصة أو الفاضية: 0
أطول قيمة في عمود الملعب: 58

['أروهيد', 'أزتيكا', 'أكرون', 'إن آر جي', 'إيه تي آند تي', 'العيناوي رحيمي طالبي حكيمي صيباري ملعب بي بي في إيه', 'بي إم أو فيلد', 'بي بي في إيه', 'بي سي بليس', 'جيليت', 'سوفاي', 'صابر ربيعة صلاح عبد المجيد ملعب إيه تي آند تي', 'كينتيرو سانشيز كامباز هيرنانديز دياز ملعب بي سي بليس', 'لومن فيلد', 'ليفاي', 'لينكون فاينانشال فيلد', 'ماوريسيو غ. غوميز غلارزا سانابريا بالبوينا كنلي ملعب جيليت', 'مرسيدس-بنز', 'ميتلايف', 'هارد روك']

In [ ]:
import re

def parse_box(box, i):
    bday = box.find("span", class_="bday")
    date = bday.get_text(strip=True) if bday else None

    ftime = box.find("div", class_="ftime")
    time_ = ftime.get_text(strip=True) if ftime else None

    full_text = box.get_text(separator=" ", strip=True)

    stadium = city = attendance = referee = referee_country = None

    idx_att = full_text.find("الحضور:")
    if idx_att != -1:
        before_att = full_text[:idx_att].strip()

        last_comma = before_att.rfind("،")
        if last_comma != -1:
            venue_part = before_att[:last_comma]
            city = before_att[last_comma + 1:].strip()

            penalty_idx = venue_part.rfind("ركلات الترجيح")
            if penalty_idx != -1:
                venue_part = venue_part[penalty_idx + len("ركلات الترجيح"):]

            m_stadium = re.search(r"([^\d\[\]'()]+)$", venue_part)
            if m_stadium:
                stadium = re.sub(r'^ملعب\s+', '', m_stadium.group(1).strip()).strip()

        rest = full_text[idx_att:]
        m_att = re.search(r'الحضور:\s*([\d,،]+)', rest)
        if m_att:
            attendance = m_att.group(1).replace(",", "").replace("،", "")

        m_ref = re.search(r'الحكم:\s*(.+?)\s*\(\s*(.+?)\s*\)', rest)
        if m_ref:
            referee, referee_country = m_ref.group(1).strip(), m_ref.group(2).strip()

    return {
        "رقم_المباراة": i + 1,
        "التاريخ": date,
        "الوقت": time_,
        "الملعب": stadium,
        "المدينة": city,
        "الحضور": attendance,
        "الحكم": referee,
        "بلد_الحكم": referee_country,
    }

match_details = [parse_box(box, i) for i, box in enumerate(football_boxes)]
match_details_df = pd.DataFrame(match_details)

print(match_details_df.shape)
print("عدد القيم الفريدة لأسماء الملاعب:", match_details_df["الملعب"].nunique())
print(sorted(match_details_df["الملعب"].unique()))

(104, 8)
عدد القيم الفريدة لأسماء الملاعب: 20
['أروهيد', 'أزتيكا', 'أكرون', 'إن آر جي', 'إيه تي آند تي', 'العيناوي رحيمي طالبي حكيمي صيباري ملعب بي بي في إيه', 'بي إم أو فيلد', 'بي بي في إيه', 'بي سي بليس', 'جيليت', 'سوفاي', 'صابر ربيعة صلاح عبد المجيد ملعب إيه تي آند تي', 'كينتيرو سانشيز كامباز هيرنانديز دياز ملعب بي سي بليس', 'لومن فيلد', 'ليفاي', 'لينكون فاينانشال فيلد', 'ماوريسيو غ. غوميز غلارزا سانابريا بالبوينا كنلي ملعب جيليت', 'مرسيدس-بنز', 'ميتلايف', 'هارد روك']

In [ ]:
for idx in [8, 9]:
    print("=" * 60)
    print(repr(football_boxes[idx].get_text(separator=" ", strip=True)))

============================================================
"18 يونيو 2026 ( 2026-06-18 ) 12:00 م ت.ع.م−7 سويسرا 4–1 البوسنة والهرسك مانزامبي 74' ، 90' فارغاس 84' تشاكا 7+90' ( ر.ج. ) [ تقرير 9 ] محميتش 90+3' ملعب سوفاي ، إنغلوود الحضور: 70,026 الحكم: جواو بينهيرو ( البرتغال )"
============================================================
"18 يونيو 2026 ( 2026-06-18 ) 3:00 م ت.ع.م−7 كندا 6–0 قطر لارين 16' ج. ديفيد 29' ، 3+45' ، 2+90' صليبا 64' المناعي 75' ( هـ.ذ. ) [ تقرير 10 ] ملعب بي سي بليس ، فانكوفر الحضور: 52،497 الحكم: كريستيان غاراي ( تشيلي )"

In [ ]:
print(repr(football_boxes[74].get_text(separator=" ", strip=True)))

"29 يونيو 2026 ( 2026-06-29 ) 4:30 م ت.ع.م−4 ألمانيا 1–1 ( ب.و.إ. ) باراغواي هافيرتس 54' [ تقرير 75 ] إنسيسكو 42' ركلات الترجيح هافيرتس كيميش موسيالا فولتماده أميري تاه 3–4 ماوريسيو غ. غوميز غلارزا سانابريا بالبوينا كنلي ملعب جيليت ، فوكسبورو الحضور: 63،945 الحكم: جلال جيد ( المغرب )"

In [ ]:
import re

def parse_box(box, i):
    bday = box.find("span", class_="bday")
    date = bday.get_text(strip=True) if bday else None

    ftime = box.find("div", class_="ftime")
    time_ = ftime.get_text(strip=True) if ftime else None

    full_text = box.get_text(separator=" ", strip=True)

    stadium = city = attendance = referee = referee_country = None

    idx_att = full_text.find("الحضور:")
    if idx_att != -1:
        before_att = full_text[:idx_att].strip()

        last_comma = before_att.rfind("،")
        if last_comma != -1:
            venue_part = before_att[:last_comma]
            city = before_att[last_comma + 1:].strip()

            # الأولوية: نلاقي آخر ظهور لكلمة "ملعب" ونقصّ بعدها مباشرة
            idx_stadium_word = venue_part.rfind("ملعب")
            if idx_stadium_word != -1:
                stadium = venue_part[idx_stadium_word + len("ملعب"):].strip()
            else:
                # لو معندهاش كلمة "ملعب" (زي حالة "لومن فيلد")، نستبعد الأرقام
                m_stadium = re.search(r"([^\d\[\]'()]+)$", venue_part)
                if m_stadium:
                    stadium = m_stadium.group(1).strip()

        rest = full_text[idx_att:]
        m_att = re.search(r'الحضور:\s*([\d,،]+)', rest)
        if m_att:
            attendance = m_att.group(1).replace(",", "").replace("،", "")

        m_ref = re.search(r'الحكم:\s*(.+?)\s*\(\s*(.+?)\s*\)', rest)
        if m_ref:
            referee, referee_country = m_ref.group(1).strip(), m_ref.group(2).strip()

    return {
        "رقم_المباراة": i + 1,
        "التاريخ": date,
        "الوقت": time_,
        "الملعب": stadium,
        "المدينة": city,
        "الحضور": attendance,
        "الحكم": referee,
        "بلد_الحكم": referee_country,
    }

match_details = [parse_box(box, i) for i, box in enumerate(football_boxes)]
match_details_df = pd.DataFrame(match_details)

print(match_details_df.shape)
print("عدد القيم الفريدة لأسماء الملاعب:", match_details_df["الملعب"].nunique())
print(sorted(match_details_df["الملعب"].unique()))

(104, 8)
عدد القيم الفريدة لأسماء الملاعب: 16
['أروهيد', 'أزتيكا', 'أكرون', 'إن آر جي', 'إيه تي آند تي', 'بي إم أو فيلد', 'بي بي في إيه', 'بي سي بليس', 'جيليت', 'سوفاي', 'لومن فيلد', 'ليفاي', 'لينكون فاينانشال فيلد', 'مرسيدس-بنز', 'ميتلايف', 'هارد روك']

In [ ]:
# دمج تفاصيل الملعب/التاريخ/الحكم مع جدول المباريات والنتائج والهدافين
final_dataset = all_matches_df.merge(match_details_df, on="رقم_المباراة", how="left")

# تنظيف عمود الوقت: نفصل الوقت عن باقي الالتصاقات
final_dataset["الوقت"] = final_dataset["الوقت"].str.extract(r"^(\d{1,2}:\d{2})")

# نرتب الأعمدة بشكل منطقي
final_dataset = final_dataset[[
    "رقم_المباراة", "التاريخ", "الوقت", "الدور",
    "الفريق1", "النتيجة", "الفريق2",
    "الملعب", "المدينة", "الحضور",
    "الحكم", "بلد_الحكم",
    "هدافي_الفريق1", "هدافي_الفريق2",
    "ركلات_ترجيح_الفريق1", "نتيجة_الركلات", "ركلات_ترجيح_الفريق2"
]]

print(final_dataset.shape)
final_dataset.head(10)

(104, 17)

,رقم_المباراة,التاريخ,الوقت,الدور,الفريق1,النتيجة,الفريق2,الملعب,المدينة,الحضور,الحكم,بلد_الحكم,هدافي_الفريق1,هدافي_الفريق2,ركلات_ترجيح_الفريق1,نتيجة_الركلات,ركلات_ترجيح_الفريق2
0,1,2026-06-11,1:00,دور المجموعات,المكسيك,2–0,جنوب إفريقيا,أزتيكا,مدينة مكسيكو,80824,ويلتون سامبايو,البرازيل,كينيونيس 9' خيمينيز 67',NaN,None,None,None
1,2,2026-06-11,8:00,دور المجموعات,كوريا الجنوبية,2–1,التشيك,أكرون,سابوبان,44985,أمين عمر,مصر,بيوم 67' هيون جيو 80',كريتشي 59',None,None,None
2,3,2026-06-18,12:00,دور المجموعات,التشيك,1–1,جنوب إفريقيا,مرسيدس-بنز,أتلانتا,67442,توري بينسو,الولايات المتحدة,سادلييك 6',موكوينا 83' (ر.ج.),None,None,None
3,4,2026-06-18,7:00,دور المجموعات,المكسيك,1–0,كوريا الجنوبية,أكرون,سابوبان,45522,غوستافو تيجيرا,أوروغواي,رومو 50',NaN,None,None,None
4,5,2026-06-24,7:00,دور المجموعات,التشيك,0–3,المكسيك,أزتيكا,مدينة مكسيكو,80824,يائيل فالكون,الأرجنتين,NaN,م. شافييز 55' كينيونيس 61' فيدالغو 90+4',None,None,None
5,6,2026-06-24,7:00,دور المجموعات,جنوب إفريقيا,1–0,كوريا الجنوبية,بي بي في إيه,غوادالوبي,51243,فاكوندو تيلو,الأرجنتين,ماسيكو 63',NaN,None,None,None
6,7,2026-06-12,3:00,دور المجموعات,كندا,1–1,البوسنة والهرسك,بي إم أو فيلد,تورونتو,43002,فاكوندو تيلو,الأرجنتين,لارين 78',لوكيتش 21',None,None,None
7,8,2026-06-13,12:00,دور المجموعات,قطر,1–1,سويسرا,ليفاي,سانتا كلارا,67966,سعيد مارتينيز,هندوراس,موهايم 4+90' (هـ.ذ.),إمبولو 17' (ر.ج.),None,None,None
8,9,2026-06-18,12:00,دور المجموعات,سويسرا,4–1,البوسنة والهرسك,سوفاي,إنغلوود,70026,جواو بينهيرو,البرتغال,مانزامبي 74'، 90' فارغاس 84' تشاكا 7+90' (ر.ج.),محميتش 90+3',None,None,None
9,10,2026-06-18,3:00,دور المجموعات,كندا,6–0,قطر,بي سي بليس,فانكوفر,52497,كريستيان غاراي,تشيلي,لارين 16' ج. ديفيد 29'، 3+45'، 2+90' صليبا 64'...,NaN,None,None,None

In [ ]:
final_dataset.to_csv("world_cup_2026_full_dataset.csv", index=False, encoding="utf-8-sig")

from google.colab import files
files.download("world_cup_2026_full_dataset.csv")

In [ ]:
print(tables[10].columns.tolist())
print(tables[10].to_string())

['م', 'الفريقعنت', 'لعب', 'ف', 'ت', 'خ', 'أ.له', 'أ.ع', 'أ.ف', 'النقاط', 'التأهل']
   م       الفريقعنت  لعب  ف  ت  خ  أ.له  أ.ع أ.ف  النقاط                        التأهل
0  1     المكسيك (H)    3  3  0  0     6    0  +6       9  يتأهل إلى مرحلة خروج المغلوب
1  2    جنوب إفريقيا    3  1  1  1     2    3  −1       4  يتأهل إلى مرحلة خروج المغلوب
2  3  كوريا الجنوبية    3  1  0  2     2    3  −1       3                           NaN
3  4          التشيك    3  0  1  2     2    6  −4       1                           NaN

In [ ]:
import re

group_names = [
    "المجموعة الأولى", "المجموعة الثانية", "المجموعة الثالثة", "المجموعة الرابعة",
    "المجموعة الخامسة", "المجموعة السادسة", "المجموعة السابعة", "المجموعة الثامنة",
    "المجموعة التاسعة", "المجموعة العاشرة", "المجموعة الحادية عشر", "المجموعة الثانية عشر",
]

standings_indices = [10, 17, 24, 31, 38, 45, 52, 59, 66, 73, 80, 87]

all_standings = []
for group_name, idx in zip(group_names, standings_indices):
    t = tables[idx].copy()
    t.insert(0, "المجموعة", group_name)
    all_standings.append(t)

standings_df = pd.concat(all_standings, ignore_index=True)

# تنظيف: نشيل علامة (H) بتاعة المضيف ونحطها في عمود منفصل
standings_df["مضيف"] = standings_df["الفريقعنت"].str.contains(r"\(H\)", na=False)
standings_df["الفريقعنت"] = standings_df["الفريقعنت"].str.replace(r"\s*\(H\)", "", regex=True)

# إعادة تسمية الأعمدة لأسماء أوضح
standings_df = standings_df.rename(columns={
    "م": "المركز_في_المجموعة",
    "الفريقعنت": "الفريق",
    "لعب": "عدد_المباريات",
    "ف": "فوز",
    "ت": "تعادل",
    "خ": "خسارة",
    "أ.له": "أهداف_له",
    "أ.ع": "أهداف_عليه",
    "أ.ف": "فارق_الأهداف",
    "النقاط": "النقاط",
    "التأهل": "التأهل",
})

print(standings_df.shape)
standings_df.head(20)

(48, 13)

,المجموعة,المركز_في_المجموعة,الفريق,عدد_المباريات,فوز,تعادل,خسارة,أهداف_له,أهداف_عليه,فارق_الأهداف,النقاط,التأهل,مضيف
0,المجموعة الأولى,1,المكسيك,3,3,0,0,6,0,+6,9,يتأهل إلى مرحلة خروج المغلوب,True
1,المجموعة الأولى,2,جنوب إفريقيا,3,1,1,1,2,3,−1,4,يتأهل إلى مرحلة خروج المغلوب,False
2,المجموعة الأولى,3,كوريا الجنوبية,3,1,0,2,2,3,−1,3,NaN,False
3,المجموعة الأولى,4,التشيك,3,0,1,2,2,6,−4,1,NaN,False
4,المجموعة الثانية,1,سويسرا,3,2,1,0,7,3,+4,7,يتأهل إلى مرحلة خروج المغلوب,False
5,المجموعة الثانية,2,كندا,3,1,1,1,8,3,+5,4[ا],يتأهل إلى مرحلة خروج المغلوب,True
6,المجموعة الثانية,3,البوسنة والهرسك,3,1,1,1,5,6,−1,4[ا],يتأهل إلى مرحلة خروج المغلوب,False
7,المجموعة الثانية,4,قطر,3,0,1,2,2,10,−8,1,NaN,False
8,المجموعة الثالثة,1,البرازيل,3,2,1,0,7,1,+6,7[ا],يتأهل إلى مرحلة خروج المغلوب,False
9,المجموعة الثالثة,2,المغرب,3,2,1,0,6,3,+3,7[ا],يتأهل إلى مرحلة خروج المغلوب,False
10,المجموعة الثالثة,3,إسكتلندا,3,1,0,2,1,4,−3,3,NaN,False
11,المجموعة الثالثة,4,هايتي,3,0,0,3,2,8,−6,0,NaN,False
12,المجموعة الرابعة,1,الولايات المتحدة,3,2,0,1,8,4,+4,6,يتأهل إلى مرحلة خروج المغلوب,True
13,المجموعة الرابعة,2,أستراليا,3,1,1,1,2,2,0,4[ا],يتأهل إلى مرحلة خروج المغلوب,False
14,المجموعة الرابعة,3,باراغواي,3,1,1,1,2,4,−2,4[ا],يتأهل إلى مرحلة خروج المغلوب,False
15,المجموعة الرابعة,4,تركيا,3,1,0,2,3,5,−2,3,NaN,False
16,المجموعة الخامسة,1,ألمانيا,3,2,0,1,10,4,+6,6[ا],يتأهل إلى مرحلة خروج المغلوب,False
17,المجموعة الخامسة,2,ساحل العاج,3,2,0,1,4,2,+2,6[ا],يتأهل إلى مرحلة خروج المغلوب,False
18,المجموعة الخامسة,3,الإكوادور,3,1,1,1,2,2,0,4,يتأهل إلى مرحلة خروج المغلوب,False
19,المجموعة الخامسة,4,كوراساو,3,0,1,2,1,9,−8,1,NaN,False

In [ ]:
import re

# تنظيف عمود النقاط: نشيل أي حاشية زي [ا] ونحوله لرقم صحيح
standings_df["النقاط"] = standings_df["النقاط"].astype(str).str.extract(r"^(\d+)")[0].astype(int)

# تأكيد إن باقي الأعمدة الرقمية كلها int (مش نصوص فيها رموز زيادة)
numeric_cols = ["عدد_المباريات", "فوز", "تعادل", "خسارة", "أهداف_له", "أهداف_عليه", "النقاط"]
for col in numeric_cols:
    standings_df[col] = pd.to_numeric(standings_df[col], errors="coerce")

print("عدد النولز في الأعمدة الرقمية:", standings_df[numeric_cols].isna().sum().sum())
print(standings_df.dtypes)
standings_df[standings_df["المجموعة"]=="المجموعة الثانية"]

عدد النولز في الأعمدة الرقمية: 0
المجموعة              object
المركز_في_المجموعة     int64
الفريق                object
عدد_المباريات          int64
فوز                    int64
تعادل                  int64
خسارة                  int64
أهداف_له               int64
أهداف_عليه             int64
فارق_الأهداف          object
النقاط                 int64
التأهل                object
مضيف                    bool
dtype: object

,المجموعة,المركز_في_المجموعة,الفريق,عدد_المباريات,فوز,تعادل,خسارة,أهداف_له,أهداف_عليه,فارق_الأهداف,النقاط,التأهل,مضيف
4,المجموعة الثانية,1,سويسرا,3,2,1,0,7,3,+4,7,يتأهل إلى مرحلة خروج المغلوب,False
5,المجموعة الثانية,2,كندا,3,1,1,1,8,3,+5,4,يتأهل إلى مرحلة خروج المغلوب,True
6,المجموعة الثانية,3,البوسنة والهرسك,3,1,1,1,5,6,−1,4,يتأهل إلى مرحلة خروج المغلوب,False
7,المجموعة الثانية,4,قطر,3,0,1,2,2,10,−8,1,NaN,False

In [ ]:
import re

# استخراج فارق الأهداف كرقم صحيح فعلي (يفيدنا في أي تحليل أو رسم بياني بعدين)
def parse_diff(val):
    val = str(val).replace('−', '-').replace('+', '')
    return int(val)

standings_df["فارق_الأهداف_رقم"] = standings_df["فارق_الأهداف"].apply(parse_diff)

# تأكيد نهائي: مفيش نولز في الملف كله
print("إجمالي النولز في الملف:", standings_df.isna().sum().sum())
print(standings_df.shape)

# تصدير
standings_df.to_csv("world_cup_2026_group_standings.csv", index=False, encoding="utf-8-sig")

from google.colab import files
files.download("world_cup_2026_group_standings.csv")

إجمالي النولز في الملف: 16
(48, 14)